name: Build and Deploy
on: [workflow_dispatch]
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron

      - name: Enable PNPM
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Configure SSH
        run: |
          echo 'echo "${{ secrets.PASSPHRASE }}"' >> ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          eval $(ssh-agent -s -a $SSH_AUTH_SOCK) > /dev/null
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null

      - name: Deploy to Server
        run: |
          scp -o 'StrictHostKeyChecking no' -P ${{ secrets.PORT }} -p backend/build/dxx-tracker-backend.mjs backend/build/*.node ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/rebirth-tracker/backend
          scp -o 'StrictHostKeyChecking no' -P ${{ secrets.PORT }} -rp frontend/dist/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/rebirth-tracker/html/
