name: Build and Deploy
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron

      - name: Enable PNPM
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Deploy Backend to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          overwrite: true
          strip_components: 2
          source: "backend/build/dxx-tracker-backend.mjs,backend/build/*.node"
          target: /var/www/rebirth-tracker/backend

      - name: Deploy Frontend to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          overwrite: true
          strip_components: 2
          source: frontend/dist/**/*,frontent/dist/*
          target: /var/www/rebirth-tracker/html

      - name: Restart Tracker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: /home/${{ secrets.USERNAME }}/.local/share/pnpm/pm2 restart dxx-tracker-backend
